import type { TextStyle as CKTextStyle } from "canvaskit-wasm";

export function TextStyle({
  backgroundColor,
  color,
  decoration,
  decorationColor,
  decorationThickness,
  decorationStyle,
  fontFamilies,
  fontFeatures,
  fontSize,
  fontStyle,
  fontVariations,
  foregroundColor,
  heightMultiplier,
  halfLeading,
  letterSpacing,
  locale,
  shadows,
  textBaseline,
  wordSpacing,
}: CKTextStyle) {
  return {
    backgroundColor,
    color,
    decoration,
    decorationColor,
    decorationThickness,
    decorationStyle,
    fontFamilies,
    fontFeatures,
    fontSize,
    fontStyle,
    fontVariations,
    foregroundColor,
    heightMultiplier,
    halfLeading,
    letterSpacing,
    locale,
    shadows,
    textBaseline,
    wordSpacing,
  };
}
